require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Naming/AsciiIdentifiers:
  Exclude:
    - 'features/step_definitions/**/*'

Style/ClassVars:
  Exclude:
    - 'spec/doubles/cisdoubles.rb'
    - 'spec/doubles/sdl2.rb'
